CREATE TABLE IF NOT EXISTS cars (
  id     SERIAL PRIMARY KEY,
  campo1 VARCHAR(255)  NOT NULL,
  campo2 VARCHAR(255)  NOT NULL,
  campo3 VARCHAR(255)  NOT NULL,
  campo4 INTEGER       NOT NULL,
  campo5 NUMERIC(10,2) NOT NULL,
  campo6 BOOLEAN       NOT NULL
);